packages:
  - 'apps/*'
  - 'packages/*'

# Нативные зависимости, которым разрешено выполнять скрипты установки
onlyBuiltDependencies:
  - argon2
  - msgpackr-extract
  - esbuild
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - '@embedded-postgres/linux-x64'
  - '@embedded-postgres/linux-arm64'
  - '@embedded-postgres/darwin-x64'
  - '@embedded-postgres/darwin-arm64'
  - '@embedded-postgres/windows-x64'
